/*
 * This source file was generated by the Gradle 'init' task
 */
package me.jamieburns;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        CleanUpFiles classUnderTest = new CleanUpFiles();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
