/*
 * This source file was generated by the Gradle 'init' task
 */
package me.jamieburns;

import org.openjdk.jol.info.ClassLayout;
import org.openjdk.jol.vm.VM;

public class App {
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(VM.current().details());
        System.out.println(ClassLayout.parseClass(A.class).toPrintable());
    }

    // https://github.com/openjdk/jol/blob/master/jol-samples/src/main/java/org/openjdk/jol/samples/JOLSample_03_Packing.java

    public static class A {
        boolean bo1, bo2;
        byte b1, b2;
        char c1, c2;
        double d1, d2;
        float f1, f2;
        int i1, i2;
        long l1, l2;
        short s1, s2;       
    }
}